# Generated by Django 5.1.15 on 2026-09-12 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConsumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g. 'prod', 'staging'", max_length=100)),
                ('key_prefix', models.CharField(help_text='First few characters of the raw key, for identification only.', max_length=12)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('scopes', models.CharField(help_text='Comma-separated, from: csp:read, balance:read, incentive:read, projection:read, transaction:read, report:read', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='api.apiconsumer')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key_hash'], name='api_apikey_key_has_ce081c_idx')],
            },
        ),
    ]
