# Generated by Django 5.1.15 on 2026-09-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='scopes',
            field=models.CharField(help_text='Comma-separated, from: csp:read, balance:read, incentive:read, projection:read, transaction:read, report:read, comparison:read', max_length=255),
        ),
    ]
