# Generated by Django 5.1.15 on 2026-09-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Csp',
            fields=[
                ('csp_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('account_count', models.PositiveIntegerField(blank=True, null=True)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('tl_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('raw_attrs', models.JSONField(blank=True, default=dict)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['csp_code'],
            },
        ),
        migrations.CreateModel(
            name='IngestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_mtime', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=10)),
                ('rows_read', models.PositiveIntegerField(default=0)),
                ('rows_valid', models.PositiveIntegerField(default=0)),
                ('rows_rejected', models.PositiveIntegerField(default=0)),
                ('rows_upserted', models.PositiveIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField()),
                ('daily_avg_balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(choices=[('calling_sheet', 'Calling sheet'), ('history', 'History backfill'), ('carry_forward', 'Carried forward')], max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('csp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_balances', to='csp.csp')),
            ],
            options={
                'ordering': ['csp_id', 'balance_date'],
                'indexes': [models.Index(fields=['csp', 'balance_date'], name='csp_dailyba_csp_id_3a3204_idx')],
                'constraints': [models.UniqueConstraint(fields=('csp', 'balance_date'), name='uniq_csp_balance_date')],
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=7)),
                ('days_in_month', models.PositiveSmallIntegerField()),
                ('days_with_data', models.PositiveSmallIntegerField()),
                ('mtd_mab', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_mab', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('slab', models.CharField(choices=[('NIL', 'Up to 2,500 (NIL)'), ('S1', '2,501-4,000 (1.10% p.a.)'), ('S2', '4,001-6,000 (1.20% p.a.)'), ('S3', '6,001-10,000 (1.25% p.a.)'), ('S4', 'Above 10,000 (1.30% p.a.)')], max_length=4)),
                ('projected_slab', models.CharField(blank=True, choices=[('NIL', 'Up to 2,500 (NIL)'), ('S1', '2,501-4,000 (1.10% p.a.)'), ('S2', '4,001-6,000 (1.20% p.a.)'), ('S3', '6,001-10,000 (1.25% p.a.)'), ('S4', 'Above 10,000 (1.30% p.a.)')], max_length=4)),
                ('incentive_rate_pa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('projected_incentive_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gap_to_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gap_to_next_slab', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prev_month_mab', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mom_change_abs', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('mom_change_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trend_7d_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trend_flag', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=10)),
                ('is_eligible', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('csp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_summaries', to='csp.csp')),
            ],
            options={
                'ordering': ['-month', 'csp_id'],
                'indexes': [models.Index(fields=['month', 'slab'], name='csp_monthly_month_e03739_idx')],
                'constraints': [models.UniqueConstraint(fields=('csp', 'month'), name='uniq_csp_month')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('ref_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('txn_datetime', models.DateTimeField()),
                ('txn_date', models.DateField()),
                ('txn_type', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('withdrawal', 'Withdrawal'), ('deposit', 'Deposit'), ('fund_transfer', 'Fund transfer')], max_length=20)),
                ('direction', models.CharField(choices=[('in_pool', 'Into pool'), ('out_pool', 'Out of pool'), ('other', 'Other')], max_length=10)),
                ('from_account', models.CharField(blank=True, max_length=32)),
                ('to_account', models.CharField(blank=True, max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('csp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='csp.csp')),
            ],
            options={
                'ordering': ['-txn_datetime'],
                'indexes': [models.Index(fields=['csp', 'txn_date'], name='csp_transac_csp_id_276029_idx')],
            },
        ),
    ]
