# Generated by Django 5.1.15 on 2026-09-12 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybalance',
            name='source',
            field=models.CharField(choices=[('calling_sheet', 'Calling sheet'), ('history', 'History backfill'), ('carry_forward', 'Carried forward'), ('demo', 'Synthetic demo data (dev only, see seed_demo_balances)')], max_length=20),
        ),
    ]
