# Generated by Django 5.1.15 on 2026-09-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0002_alter_dailybalance_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='csp',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
