# Generated by Django 5.1.15 on 2026-09-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0003_csp_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybalance',
            name='account_count',
            field=models.PositiveIntegerField(blank=True, help_text="CSP's total account count as of this day's reading.", null=True),
        ),
    ]
