# Generated by Django 5.1.15 on 2026-09-18 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0004_dailybalance_account_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCspSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('mtd_avg_so_far', models.DecimalField(decimal_places=2, max_digits=14)),
                ('days_with_data_mtd', models.PositiveSmallIntegerField(default=0)),
                ('slab', models.CharField(choices=[('NIL', 'Up to 2,500 (NIL)'), ('S1', '2,501-4,000 (1.10% p.a.)'), ('S2', '4,001-6,000 (1.20% p.a.)'), ('S3', '6,001-10,000 (1.25% p.a.)'), ('S4', 'Above 10,000 (1.30% p.a.)')], max_length=4)),
                ('incentive_rate_pa', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('gap_to_min', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gap_to_next_slab', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('is_eligible', models.BooleanField(default=False)),
                ('data_status', models.CharField(choices=[('fresh', 'Fresh'), ('delayed', 'Delayed'), ('stale', 'Stale'), ('no_data', 'No data')], default='no_data', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-business_date', 'csp_id'],
            },
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='external_ref',
            field=models.CharField(blank=True, help_text='Telegram message_id/file_id, or blank for other sources.', max_length=255),
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='rows_duplicate',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='rows_unmapped_csp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestlog',
            name='source_hash',
            field=models.CharField(blank=True, help_text='sha256 of the source file/payload, for file-level dedup.', max_length=64),
        ),
        migrations.AlterField(
            model_name='ingestlog',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('received', 'Received'), ('processing', 'Processing'), ('duplicate_skipped', 'Duplicate, skipped'), ('invalid_source', 'Invalid source')], default='success', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ingestlog',
            index=models.Index(fields=['source_hash'], name='csp_ingestl_source__7780de_idx'),
        ),
        migrations.AddField(
            model_name='dailycspsnapshot',
            name='csp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='csp.csp'),
        ),
        migrations.AddIndex(
            model_name='dailycspsnapshot',
            index=models.Index(fields=['business_date', 'slab'], name='csp_dailycs_busines_e1de91_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailycspsnapshot',
            constraint=models.UniqueConstraint(fields=('csp', 'business_date'), name='uniq_csp_snapshot_date'),
        ),
    ]
