# Generated by Django 5.1.15 on 2026-09-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csp', '0005_dailycspsnapshot_ingestlog_external_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestlog',
            name='external_ref',
            field=models.CharField(blank=True, help_text='Telegram update_id, or blank for other sources.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ingestlog',
            name='source_hash',
            field=models.CharField(blank=True, help_text="Content fingerprint for file-level dedup: sha256 for folder-watch files, Telegram's own file_unique_id for Telegram-delivered ones.", max_length=64),
        ),
    ]
