# Generated by Django 5.1.15 on 2026-09-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilot', '0001_initial'),
        ('csp', '0006_alter_ingestlog_external_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(default='csp_operations_agent', max_length=100)),
                ('task', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('needs_data', 'Needs data'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.JSONField(blank=True, default=dict)),
                ('tools_used', models.JSONField(blank=True, default=list)),
                ('reasoning_summary', models.TextField(blank=True, default='')),
                ('action_plan', models.TextField(blank=True, default='')),
                ('final_status', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('message_draft', 'Message draft'), ('followup_task', 'Follow-up task'), ('escalation', 'Escalation recommendation'), ('review_flag', 'Marked for review'), ('investigation', 'Investigation task')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('executed', 'Executed'), ('failed', 'Failed'), ('needs_review', 'Needs review')], default='proposed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_result', models.TextField(blank=True, default='')),
                ('csp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='csp.csp')),
                ('draft_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='autopilot.draftmessage')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='autopilot.agentrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_calls', to='autopilot.agentrun')),
            ],
            options={
                'ordering': ['called_at'],
            },
        ),
    ]
