# Generated by Django 5.1.15 on 2026-09-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autopilot', '0002_agentrun_agentaction_agenttoolcall'),
        ('csp', '0006_alter_ingestlog_external_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_agent', models.CharField(max_length=100)),
                ('target_agent', models.CharField(blank=True, default='', max_length=100)),
                ('finding_type', models.CharField(max_length=100)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(max_length=200)),
                ('data_timestamp', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs review'), ('insufficient_data', 'Insufficient data'), ('conflicting_data', 'Conflicting data'), ('stale_data', 'Stale data')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('csp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='csp.csp')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentaction',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='autopilot.agentfinding'),
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('needs_data', 'Needs data'), ('failed', 'Failed')], default='running', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(blank=True, default='', max_length=255)),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replans', to='autopilot.agenttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_agent', models.CharField(max_length=100)),
                ('to_agent', models.CharField(max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='autopilot.agenttask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentfinding',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='autopilot.agenttask'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='task_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='autopilot.agenttask'),
        ),
        migrations.CreateModel(
            name='AgentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verifier_agent', models.CharField(default='verification_agent', max_length=100)),
                ('result', models.CharField(choices=[('verified', 'Verified'), ('rejected', 'Rejected'), ('needs_review', 'Needs review')], max_length=20)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='autopilot.agentfinding')),
            ],
            options={
                'ordering': ['-verified_at'],
            },
        ),
    ]
